#!/usr/bin/env python

from time import sleep
import RPi.GPIO as GPIO
import sys
from random import sample

# GPIO Channels
RED_OUT, YELLOW_OUT, GREEN_OUT, BLUE_OUT = 7, 11, 13, 15

PATTERNS = [
	# Back and Forth
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:1,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:0,YELLOW_OUT:1,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:1,BLUE_OUT:0},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:1},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:1,BLUE_OUT:0},
	{RED_OUT:0,YELLOW_OUT:1,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:1,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:0,YELLOW_OUT:1,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:1,BLUE_OUT:0},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:1},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:1,BLUE_OUT:0},
	{RED_OUT:0,YELLOW_OUT:1,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:1,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:0,YELLOW_OUT:1,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:1,BLUE_OUT:0},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:1},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:1,BLUE_OUT:0},
	{RED_OUT:0,YELLOW_OUT:1,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:0},

	# FLash
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:1,YELLOW_OUT:1,GREEN_OUT:1,BLUE_OUT:1},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:1,YELLOW_OUT:1,GREEN_OUT:1,BLUE_OUT:1},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:1,YELLOW_OUT:1,GREEN_OUT:1,BLUE_OUT:1},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:0},

	# Twos
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:1,YELLOW_OUT:1,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:1,BLUE_OUT:1},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:0,YELLOW_OUT:1,GREEN_OUT:1,BLUE_OUT:0},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:1,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:1},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:1,YELLOW_OUT:1,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:1,BLUE_OUT:1},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:0,YELLOW_OUT:1,GREEN_OUT:1,BLUE_OUT:0},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:1,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:1},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:1,YELLOW_OUT:1,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:1,BLUE_OUT:1},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:0,YELLOW_OUT:1,GREEN_OUT:1,BLUE_OUT:0},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:0},
	{RED_OUT:1,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:1},
	{RED_OUT:0,YELLOW_OUT:0,GREEN_OUT:0,BLUE_OUT:0},
]

def run():
	init()

	# Ucomment to cleanup after running
	#GPIO.cleanup
	#exit()

	loop = True

	p = 0

	while loop:
		pat = PATTERNS[p]
		lights(pat)
		sleep(.15)
		p = p + 1
		if p >= len(PATTERNS):
			p = 0

def init():
	# GPIO
	GPIO.setwarnings(False)
	GPIO.setmode(GPIO.BOARD)

	for pin in [RED_OUT, YELLOW_OUT, GREEN_OUT, BLUE_OUT]:
		GPIO.setup(pin, GPIO.OUT, initial=GPIO.HIGH)

def lights(colors):
	for pin in colors:
		if colors[pin]:
			GPIO.output(pin,GPIO.LOW);
		else:
			GPIO.output(pin,GPIO.HIGH);

run()
